site_name: Smarty Documentation
theme:
  name: material
  palette:
    primary: amber
  features:
    - content.code.copy
  icon:
    logo: material/lightbulb-on
  favicon: images/favicon.ico

extra:
  version:
    provider: mike

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
